version: '3'
services:
  postgres:
    restart: unless-stopped
    image: postgres:10
    env_file:
      - compose/postgres.env
    volumes:
      - pg_data:/var/lib/postgresql/data
      - /tmp/pg:/tmp/pg
    ports:
      - 5432/tcp

  api:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./compose/Dockerfile
    env_file:
      - compose/postgres.env
    ports:
      - 8000:8000/tcp
    volumes:
      - .:/code


volumes:
  pg_data:
